   <?php
/* 0*
*  © Argo Almacenadora ®
 *  Fech a: 28/12/2018
* Developer:  Jorge Tejeda J.
* Proyecto: Dashboard Ta lento Humano
* Ve  rsion  --
LA VERSION MA S REALISTA DEL MUNDO ES UN MUNDO FALSO HECHO MEDIANTE UNA MATRIZ DONDE TTODOS SOMOS UNAS SIMULACIONES

*/

include_once '../libs/conOra.php';
if(isset($_POST["encuesta"]))
{
	$encuesta = $_POST["encuesta"];
}
else {
	$encuesta = 0;
}
		$conn = conexion::conectar();
		$res_array = array();


		$sql = "SELECT ENCD.ID_CONSECUTIVO,
						CASE WHEN ENCP.TIPO_PREGUNTA = 3 THEN
						(SELECT ENDS.SUBPREGUNTA FROM AD_SGC_ENCUESTA_SUBPREGUNTA ENDS WHERE ENDS.ID_SUBPREGUNTA = ENCD.ID_SUBPREGUNTA AND ENDS.ID_PREGUNTA = ENCP.ID_PREGUNTA AND ENCP.TIPO_ENCUESTA = ENDS.TIPO_ENCUESTA)
						     WHEN ENCP.TIPO_PREGUNTA <> 3 THEN
						                        ENCP.PREGUNTA
						     END AS PREGUNTA,
						ENCP.RESP_SIONO,
						ENCR.RESPUESTA,
						ENCR.RESPUESTA2,
						ENDS.SUBPREGUNTA,
						CASE
						    WHEN ENCP.RESP_SIONO = ENCR.RESPUESTA THEN 'NEGATIVA'
						    WHEN ENCP.RESP_SIONO <> ENCR.RESPUESTA THEN 'POSITIVA'
						END AS TIPO_RES
			 			FROM AD_SGC_ENCUESTA_ENC ENCE
						INNER JOIN AD_SGC_ENCUESTA_TIPO_CLIENTE EC ON  EC.ID_CLIENTE = ENCE.ID_CLIENTE AND EC.ID_TIPO = ENCE.ENCUESTA_TIPO AND EC.IID_ENCUESTA = ENCE.IID_ENCUESTA
						INNER JOIN AD_SGC_ENCUESTA_DET ENCD ON ENCE.CONSECUTIVO_ENC = ENCD.CONSECUTIVO_ENC
						INNER JOIN AD_SGC_ENCUESTA_PREGUNTA ENCP ON ENCP.ID_PREGUNTA =  ENCD.ID_PREGUNTA AND ENCE.ENCUESTA_TIPO = ENCP.TIPO_ENCUESTA AND ENCP.IID_CONSECUTIVO = ENCD.ID_CONSECUTIVO
						LEFT OUTER JOIN AD_SGC_ENCUESTA_SUBPREGUNTA ENDS ON ENDS.ID_SUBPREGUNTA = ENCD.ID_SUBPREGUNTA AND ENDS.ID_PREGUNTA = ENCP.ID_PREGUNTA AND ENCP.TIPO_ENCUESTA = ENDS.TIPO_ENCUESTA
						INNER JOIN AD_SGC_ENCUESTA_RESPUESTA ENCR ON ENCR.ID_RESPUESTA = ENCD.ID_RESPUESTA
						WHERE ENCE.CONSECUTIVO_ENC =  $encuesta ORDER BY ENCD.ID_CONSECUTIVO , ENCD.ID_SUBPREGUNTA";

						#echo $sql;

		$stid = oci_parse($conn, $sql);
		oci_execute($stid);

		while (($row = oci_fetch_assoc($stid)) != false)
		{
			$res_array[]= $row;
		}


		oci_free_statement($stid);
		oci_close($conn);

		//echo $sql;
		echo json_encode($res_array);
		return $res_array;

?>
